### ISSUE TITLE
Doesn't work in Visual Studio 2017 15.6.4

### ISSUE THREAD

**Issue by duytech** [natehitze/SeeUsingsLater#3]
Hi Hitze,

This extension doesn't work anymore.
My VS is 2017 15.6.4.
Could you fix it?

Cheers,
Duy

**Comment by ChrisBertrandDotNet** [comment]
@duytech 
I proposed a fix here: https://github.com/natehitze/SeeUsingsLater/pull/4
That affects two lines of code only.

**Comment by natehitze** [comment]
@duytech Thank you for reporting, and I apologize for the delay in getting this fixed. I have released a new version on the marketplace that should fix this for you.

@ChrisBertrandDotNet Thank you for fixing this!

**Comment by ChrisBertrandDotNet** [comment]
@natehitze 
Thank you for merging.
