### ISSUE TITLE
Plans to upgrade this to Visual Studio 2022?

### ISSUE THREAD

**Issue by yasinkavakli** [natehitze/SeeUsingsLater#6]
Hi,

first of all, thanks for this extensions. It's really useful for VS 2019.
Do you have any plans to upgrade this to VS 2022?

Thanks in advance.

**Comment by natehitze** [comment]
I've just pushed a preview version for VS 2022 here: https://marketplace.visualstudio.com/items?itemName=Nhitze.SeeUsingsLaterx64

I had to publish to a separate package on the Marketplace due to limitations they have currently.

**Comment by yasinkavakli** [comment]
Works for me 👍
Thanks 🙏
