### ISSUE TITLE
Issue with File-scoped namespace declaration when namespace is declared first

### ISSUE THREAD

**Issue by ryanbuening** [natehitze/SeeUsingsLater#7]
It doesn't appear that the extension will collapse the using statements for a C# file that has the following:

```csharp
namespace Foo;

using System;
using System.Linq;

public class Bar
{

}
```

**Comment by natehitze** [comment]
I think this is a "bug" in Visual Studio 2022. When I entered your example code into VS2022 Preview 4 I couldn't even manually collapse the `using`s. This extension basically just automates clicking the `[-]` button to collapse the `using`s section so there's not much I can do about it currently.
